name: Publish GitHub Release
on:
  push:
    paths:
      - 'linux-cachyos/PKGBUILD'
  workflow_dispatch:

jobs:
  jobby:
    runs-on: ubuntu-latest
    container:
      image: cachyos/cachyos
    defaults:
      run:
        shell: /usr/bin/fish {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Release
      run: |
        echo $SHELL
        ls /usr/bin
