name: Publish GitHub Release
on:
  push:
    paths:
      - 'linux-cachyos/PKGBUILD'
  workflow_dispatch:

jobs:
  jobby:
    runs-on: ubuntu-latest
    container:
      image: cachyos/cachyos
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Release
      run: |
        echo $SHELL
